const baseUrl="https://9238-2401-4900-4e69-ee9c-e1f6-3055-381b-1b09.ngrok-free.app/api/"

export const TEST_URL=baseUrl+"test"

export const USER_LOGIN_URL=baseUrl+"auth/user/login"
export const USER_REGISTER_URL=baseUrl+"auth/user/register"
export const OTP_URL=baseUrl+"auth/user/register/otp/verify"
export const PROFILE_URL=baseUrl+"profile/user"
export const RECIPE_URL_ALL=baseUrl+"recipe/all"
export const RECIPE_URL_ADD=baseUrl+"recipe/new"
export const RECIPE_URL_DELETE=baseUrl+"recipe/delete"
export const RECIPE_URL_EDIT=baseUrl+"recipe/edit"
export const POST_INV_URL=baseUrl+"inventory/user"
export const POST_ADD_INV_URL=baseUrl+"inventory/"
export const PUT_EDIT_INV_URL=baseUrl+"inventory/"
export const DELETE_INV_URL=baseUrl+"inventory/"